POST http://127.0.0.1:8080/node/register
Content-Type: application/json

{
  "name": "Sample 1"
}

###
GET http://127.0.0.1:8080/node
Accept: application/json

###
GET http://127.0.0.1:8080/node/1
Accept: application/json