POST http://127.0.0.1:4444/provider/add
Content-Type: application/json

{
  "name": "Test Provider",
  "phone": {
    "countryCode": "+91",
    "phoneNumber": "1234123412"
  },
  "location": {
    "lat": -0.1,
    "lon": -0.2
  },
  "services": ["tag1", "tag2"],
  "areaServed": {
    "source": {
      "lat": -0.9,
      "lon": -0.8
    },
    "radius": 10.0
  },
  "status": "INACTIVE"
}

###
GET http://127.0.0.1:4444/provider/all
Accept: application/json

###
GET http://127.0.0.1:4444/provider/dummy
Accept: application/json

###
GET http://127.0.0.1:4444/provider/services
Accept: application/json